---
- name: Configure firewalld rules for required services and ports
  hosts: all
  become: yes
  tasks:
  - name: Ensure firewalld services are enabled permanently
    ansible.posix.firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    loop:
    - ssh
    - cockpit
    - https

  - name: Open custom HTTP ports permanently
    ansible.posix.firewalld:
      port: "{{ item.port }}"
      state: enabled
      permanent: true
      immediate: true
    loop:
    - { name: "custom-http-9392", port: "9392/tcp" }

  - name: Open syslog port 514 permanently
    ansible.posix.firewalld:
      port: "{{ item.port }}"
      state: enabled
      permanent: true
      immediate: true
    loop:
    - { name: "syslog-tcp", port: "514/tcp" }
    - { name: "syslog-udp", port: "514/udp" }

  - name: Open Zabbix Agent port permanently
    ansible.posix.firewalld:
      port: "{{ item.port }}"
      state: enabled
      permanent: true
      immediate: true
    loop:
    - { name: "zabbix-agent", port: "10050/tcp" }
