
---
- name: Setup samba server
  hosts: cortez
  remote_user: admin
  become: yes

  tasks:
  - name: update all packages
    dnf:
      name: "*"
      state: latest

  - name: Ensure cockpit packages exist
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - attr
    - bind-utils
    - docbook-style-xsl
    - gcc
    - gdb
    - krb5-workstation
    - libsemanage-python
    - libxslt
    - perl 
    - perl-ExtUtils-MakeMaker
    - perl-Parse-Yapp 
    - perl-Test-Base 
    - pkgconfig 
    - policycoreutils-python
    - python-crypto 
    - gnutls-devel
    - gpgme-devel 
    - jansson-devel 
    - libattr-devel 
    - keyutils-libs-devel 
    - libacl-devel 
    - libaio-devel 
    - libblkid-devel
    - libxml2-devel 
    - openldap-devel 
    - pam-devel 
    - popt-devel 
    - python2-devel
    - readline-devel 
    - systemd-devel 
    - zlib-devel 