---
- name: "remove existing non-docker-ce install"
  include_tasks: 0_removals.yml

- name: "docker-ce repository"
  include_tasks: 1_repository.yml

- name: "install docker"
  include_tasks: 2_install.yml

- name: "configure docker"
  include_tasks: 3_config.yml
