---
ansible_python_interpreter: /usr/bin/python3

basic:
  - nano
  - htop
  - chromium
  - nmap

ansible:
  - ansible
#  - molecule

gnome:
  - gnome-tweak-tool
  - gnome-todo
  - gnome-music
  - dconf-editor

development:
  - tig
  - git
  - python3
  - https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm
  - postgresql

productivity:
  - calibre
  - inkscape
  - libreoffice
  - vlc 
  - remmina
  - gscan2pdf
  - keepass
  - firewall-config

flatpak:
  - ca.desrt.dconf-editor
  - com.jetbrains.PyCharm-Community
  - com.mattermost.Desktop
  - com.visualstudio.code
  - com.github.donadigo.appeditor
 # - org.freedesktop.Platform
  - org.freedesktop.Platform.html5-codecs
  - org.freedesktop.Sdk
  - org.gnome.Platform
  - org.inkscape.Inkscape
  - org.libreoffice.LibreOffice
  - org.videolan.VLC
  - com.calibre_ebook.calibre

virtualisation:
  - "@virtualization"

removal:
  - rhythmbox
  - shotwell
  - evolution
  - boxes
  - virtualbox

rpmfusion:
    _dnf:
     - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm 
     - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    _rpm_ostree:  
     - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm 
     - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

powershell:
