---
# This Playbook would deploy the whole northernlights infra. 
# may also be named site.yml, as it is more neutral?



# checking, if the group name must be present:
# group "all-dem-servers" exists only on finch,
# group "validators" will exist only on serenity
# "validators" being a group of hosts used to validate playbooks, duh...



- hosts: build-server
  roles:
  - role: jenkins  

# - hosts: northernlights -> this references the group defined in inventory -> all servers are for example in the "nothernlights" group
#- hosts: arbitrary_group_name
#  roles:
#  - role: common

- hosts: commons
  roles:
  - role: common

- hosts: authentication-server
  roles:
  - role: authentication  