---

# conditional
tasks:
- name: "Install qemu guest agent"
  ansible.builtin.dnf:
    name: "qemu-guest-agent"
    state: present
  when: ansible_facts['ansible_virtualization_role'] == "guest" and ansible_facts['ansible_virtualization_type'] == "kvm"

- name: "Install qemu guest agent"
  ansible.builtin.dnf:
    name: "qemu-guest-agent"
    state: present
  when: ansible_facts['ansible_virtualization_role'] == "guest" and ansible_facts['ansible_virtualization_type'] == "kvm"