---

- name: "install SELinux recommends"
  dnf:
    name: "{{ install.selinux }}"
    state: latest

- name: "Install monitoring software"
  dnf: 
    name: "{{ install.monitor }}"
    state: present

- name: "Install basics"
  dnf: 
    name: "{{ install.default }}"
    state: present
    
- name: "Install Powerline for pleasant commandline operation"
  dnf: 
    name: "{{ install.powerline }}"
    state: present
    
# bashrc
- name: "create a decent bashrc"
  include: bashrc.yml    

# tasks file for common
- name: "harden the ssh daemon"
  include: harden-ssh.yml    

# other dotfiles?
- name: "add dotfiles"
  include: dotfiles.yml