---

- name: "Allow editing on an SELinux enforced system"
  dnf:
    name: libselinux-python3
    state: latest

- name: "install SELinux manage"
  dnf:
    name: policycoreutils-python-utils
    state: latest

- name: "Install monitoring software"
  dnf: 
    name: ['htop','sysstat', 'iotop', 'dmidecode']
    state: present

- name: "Install basics"
  dnf: 
    name: [ 'nano','python3' ]
    state: present
    
- name: "Install Powerline for pleasant commandline operation"
  dnf: 
    name: ['powerline','powerline-fonts'] 
    state: present
    
# bashrc
- name: "create a decent bashrc"
  include: bashrc.yml    

# tasks file for common
- name: "harden the ssh daemon"
  include: harden-ssh.yml    

# other dotfiles?
- name: "add dotfiles"
  include: dotfiles.yml