---

- name: Install (local) monitoring software
  dnf: 
    name: ['htop','sysstat','iotop','dmidecode']
    state: present

- name: update all packages
  dnf:
    name: "*"
    state: latest

- name: Allow editing on an SELinux enforced system
  dnf:
    name: libselinux-python
    state: latest

- name: Install basics
  dnf: 
    name: ['nano','python3','python']
    state: present

    
- name: "Install Powerline for pleasant commandline operation"
  dnf: 
    name: ['powerline','powerline-fonts'] 
    state: present

# - name: "edit .bashrc to enable powerline usage"
#   blockinfile:
#     path: /etc/bashrc.d/powerline.sh
#     block: |
#       if [ -f `which powerline-daemon` ]; then
#         powerline-daemon -q
#         POWERLINE_BASH_CONTINUATION=1
#         POWERLINE_BASH_SELECT=1
#         . /usr/share/powerline/bash/powerline.sh
#       fi

- name: Remove unwanted default packages 
  dnf: 
    name: ['rhythmbox','shotwell','builder']
    state: absent

- name: "Ensure cockpit packages exist"
  dnf:
    name: ['cockpit','cockpit-dashboard','cockpit-shell','cockpit-ws']
    state: latest


# bashrc
- name: 'do stuff to the bashrc'
  import_tasks: roles/common/tasks/bashrc.yml    

# tasks file for server_common
- name: added in 2.4, previously you used 'include'
  import_tasks: roles/common/tasks/harden-ssh.yml    