---

  - name: "Linux version info"
    debug: 
      var: 'ansible_facts.distribution_major_version'

  - name: "Install the DNF plugin"
    dnf:
      name: dnf-plugin-system-upgrade
      state: latest  

  - name: "execute the download of new packages"
    block:

    - name: "Update software and back up your system"
      shell: /usr/bin/dnf upgrade --refresh -y
    - name: "Start the update with the download of packages"
      shell: /usr/bin/dnf system-upgrade download --allowerasing --assumeyes --releasever=30     

    when: ansible_facts[distribution_major_version] =! "30" 
