---
- name: EXPLAINER FOR DEBUGGING / MESSAGE FROM SYSTEMS - HOW TO
  hosts: magellan
  remote_user: admin
  become: yes

  tasks:

    # [-----------------------------------------]
    # ANSIBLE_FACTS
    #   returns a lot of info about the host
    #   can be disabled by adding to playbook
    #   - hosts: host_everything_is_known_about
    #     gather_facts: no
    # (may increase scaling factor when managing a large number of remotes)

    - name: "ANSIBLE_FACTS: use as variable"
      file:
        path: /tmp/file-made-with-debugging-playbook.on-{{ ansible_facts['nodename'] }}.txt
        state: touch
        mode: 0644

    - debug: 
        var: ansible_facts.distribution_major_version
    - debug: 
        var: ansible_facts.distribution
    - debug:    
        var: ansible_facts.selinux.status
    - debug:    
        var: ansible_facts['selinux']['status']        

    # [-----------------------------------------]
    # LOCAL_FACTS
    #   are read from "local" (remote box!) file on remote host
    #   obviously these could be copied as well

    - name: "LOCAL_FACTS: create a local ansible preferences directory"
      file:
        path: /etc/ansible/facts.d
        state: directory
      tags: use_local_facts

    - name: "LOCAL_FACTS: create a local ansible preferences file"     
      file:
        path: /etc/ansible/facts.d/local.fact
        state: touch
        mode: 0644
      tags: use_local_facts

    - name: "LOCAL_FACTS: fill local ansible preferences file with sample data"
      blockinfile:
        path: /etc/ansible/facts.d/local.fact
        block: |
          [motd]
          mariadb: op
          postgresql: op
          zabbix: test
          [{{ ansible_facts['nodename'] }}]
          testy: test
      tags: use_local_facts

    #  even though we named the file "local.fact", one needs to query for "preferences"
    - debug: 
        var: ansible_local
    - debug:    
        var: ansible_local.preferences.motd.zabbix
    - debug:    
        var: ansible_local['preferences']['{{ ansible_facts['nodename'] }}']['testy']  