---
- name: "LOOPS (https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html)"
  hosts: "magellan"
  gather_facts: yes
  become: yes

  tasks:
  - name: add several users in a loop
    user:
      name: "{{ item }}"
      state: present
      groups: "users"
    loop:
       - finch
       - reese
       - simmons
       - wheeler

  - name: remove several users again
    user:
      name: "{{ item }}"
      state: absent
      groups: "users"
    loop:
       - finch
       - reese
       - simmons
       - wheeler

  - name: add several users from external YAML file
    include_vars:
      dir: src
      name: ext_users
      files_matching: externalised_list_var.yaml
      user:
        name: "{{ item }}"
        state: present
        groups: "users"
      loop: 
        - ext_users.user.name
    tags: 2nd