---
- name: _GET FILE INFO USING... 
  hosts: localhost
  become: yes

  tasks:
  - name: ...USING SLURP
    slurp:
      src: /etc/os-release
    register: release

  - name: Print Release Information
    debug: 
      msg: "{{ release['content'] | b64decode }}"
