---
- name: "how to manipulate variables"
  hosts: localhost
  remote_user: benno
  become: no

  tasks:
    - name: "include the variables"
      include_vars:
        file: /home/benno/ambient-lights/_vars/list.yml
#          - /home/benno/ambient-lights/_vars/externalised_var.yml
        name: variables

    - name: "get the contents of variables"
      debug:
        msg: "{{ variables }}"

    - name: "do stuff to it"
      debug:
        msg: "{{ variables | flatten }}"
    - name: "do stuff to it"
      debug:
        msg: "{{ variables | list }}"

    - name: "do stuff to it"
      debug:
        msg: "{{ variables | list }}"
    - name: "do stuff to it"
      debug:
        msg: "{{ variables | to_nice_json }}"

    - name: "do semi-raw stuff to it"
      command: echo "{{ variables | list }}"

    - name: "echo to thingy"
      shell: |
        echo "dis gon be gud. {{ variables.serenity | join(" ") }}" >> /home/benno/ambient-lights/_utils/_vars.txt
