---
# referenced in _vars.yml

# VALID VARIABLE NAMES:
# YAML supports dictionaries which map keys to values. For instance:
filetype:
  video: mp4
  audio: mp3
  text: txt
  pdf: pdf
  word: docx

# You can then reference a specific field in the dictionary using either bracket notation 
# or dot notation

# filetype['audio']
# filetype.audio
# example see _debug.message.yml

# BUT:
# However, if you choose to use dot notation be aware that some keys can cause problems 
# because they collide with attributes and methods of python dictionaries. 
# You should use bracket notation instead of dot notation if you use keys
# which start and end with two underscores

