---
# tasks file for workstation_common
# - name: "Determine Build"
#   debug:
#    var: ansible_facts

- name: "run the dnf playbook"
  include: "dnf.yml"
  when:
      - ansible_facts['pkg_mgr'] == "dnf"

- name: "run the atomic playbook"
  include: "rpm-ostree.yml"
  when:
      - ansible_facts['pkg_mgr'] == "atomic_container"

- name: "Install GUI applications as Flatpaks"
  include: "flatpak.yml"
  when:
      - ansible_facts['pkg_mgr'] == "atomic_container"  
