---
# tasks file for workstation_common
# - name: "Determine Build"
#   debug: 
#    var: ansible_facts

 - name: "Determine package Manager"
   debug: 
    var: ansible_facts.pkg_mgr

# update and basics 
 - include: "defaults.yml"    