---
- name: Add Repository for Microsoft VS CODE
  yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes
    
- name: Install visual studio code
  dnf: 
    name: code
    state: latest

- name: Add Repository for Powershell
  yum_repository:
    name: microsoft
    description: Microsoft Repository
    baseurl: "https://packages.microsoft.com/config/rhel/7/prod.repo"

#- name: Install the PowerShell Package
#  dnf:
#    name: powershell
#    state: latest