---
ansible_python_interpreter: /usr/bin/python3

basic:
  - nano
  - htop
  - chromium
  - nmap

ansible:
  - ansible
  - molecule

development:
  - tig
  - git
  - python3
  - jupyter

flatpak:
  - ca.desrt.dconf-editor
  - com.jetbrains.PyCharm-Community
  - com.mattermost.Desktop
  - com.visualstudio.code
  - com.github.donadigo.appeditor
 # - org.freedesktop.Platform
  - org.freedesktop.Platform.html5-codecs
  - org.freedesktop.Sdk
  - org.gnome.Platform
  - org.inkscape.Inkscape
  - org.libreoffice.LibreOffice
  - org.videolan.VLC
  - com.calibre_ebook.calibre

virtualisation:
  - libvirt
  - libvirt-client
  - libvirt-viewer