# tasks file for pycharm
---
- name: Get latest release information from jetbrains
  uri:
    url: https://data.services.jetbrains.com/products/releases?code=PCC&type=release
    method: GET
  register: jetbrains

- name: Unpack install archive from remote source (jetbrains-download server)
  unarchive:
    src: "{{ jetbrains.json.PCC[0].downloads.linux.link }}"
    dest: /home/admin
    remote_src: yes

- name: fix permissions
  file:
    path: /home/admin/
    owner: admin
    group: admin
    recurse: yes