---
# defaults file for server_common
ansible_python_interpreter: /usr/bin/python3

# dotfiles to use
dotfile:
 - ssh
 - bashrc
 - bash_profile
 - bash_logout
 
install:
    default:
     - nano
     - fail2ban
     - zstd
    monitor:
     - htop
     - sysstat
     - iotop
     - dmidecode
    selinux:
     - selinux
     - libselinux-python3  
     - policycoreutils-python-utils
    powerline:
     - powerline
     - powerline-fonts 
