#   - Groups of hosts are delimited by [header] elements
#   - You can enter hostnames or ip addresses
#   - A hostname/ip can be a member of multiple groups

---
all:
  hosts:
    hankscorpio:
      ansible_user: admin
      ansible_become: yes
    localhost:
      ansible_user: admin
      ansible_become: yes

workstations:
  hosts:
    hankscorpio:
      ansible_user: admin
      ansible_become: yes
