#   - Groups of hosts are delimited by [header] elements
#   - You can enter hostnames or ip addresses
#   - A hostname/ip can be a member of multiple groups

---
all:
  hosts:
    kramergasse:
      ansible_user: kramergasse
      ansible_become: yes

workstations:
  hosts:
    kramergasse:
      ansible_user: kramergasse
      ansible_become: yes
