---
# handlers file for ansible-guacamole
- name: kill guacd
  command: pkill guacd
  become: true

- name: restart guacd
  service:
    name: guacd
    state: restarted
  become: true

- name: restart tomcat
  service:
    name: tomcat
    state: restarted
  become: true

- name: restart tomcat7
  service:
    name: tomcat7
    state: restarted
  become: true

- name: restart tomcat8
  service:
    name: tomcat8
    state: restarted
  become: true

- name: restart tomcat9
  service:
    name: tomcat9
    state: restarted
  become: true
