---
# This Playbook would deploy the whole northernlights infra. 
# may also be named site.yml, as it is more neutral?

# - hosts: northernlights -> this references the group defined in inventory -> all servers are for example in the "nothernlights" group
- hosts: arbitrary_group_name
  roles:
  - role: server_common

- hosts: server_auth
  roles:
  - role: server_common
  - role: server_auth