---
- name: create all prerequisites for an installation
  hosts: localhost
  become: yes

  vars_files:
    - "{{ playbook_dir }}/special/variables.yml"

  vars_prompt:
    - name: domain_password
      prompt: Provide your AD login password for internal.northern-lights.one

  tasks:
    - name: Create a user group 
      group: name="{{customer.group}}"

    - name: "Create the {{ customer.user }} user"
      user:
        name: "{{customer.user}}"
        group: "{{customer.group}}"
        shell: "/usr/bin/bash"
        comment: "user {{customer.user}} for customer"
        createhome: "yes"
        state: present

    - name: "create a (for now unused) directory"    
      file:
        path: "/var/home/{{ customer.user }}"
        state: directory
        owner: "{{ customer.user }}"
        group: "{{ customer.group }}"
        mode: 0755 

    - name: "Download the base installation files"
      unarchive:
        src: ftp://{{ ftp.user }}:{{ ftp.password }}@{{ ftp.server }}/FTP/<user>/install.zip
        dest: "/var/home/{{ customer.user }}"
        remote_src: yes
        owner: "{{ customer.user }}"
        group: "{{ customer.group }}"
        creates: "/var/home/{{ customer.user }}/northern-lights"

  #  - name: "Download the customer build for customer {{ customer.user }}"
  #    fetch:
  #      src: ftp://{{ corp.user }}:{{ domain_password }}@{{ corp.server }}{{ corp.path }}/installer.jar
  #      dest: "/var/home/{{ customer.user }}"
  #      remote_src: yes
  #      creates: "/var/home/{{ customer.user }}/northern-lights"    

    - name: "Download a licence file"
      fetch:
        src: sftp://{{ ftp.user }}:{{ ftp.password }}@{{ ftp.server }}/FTP/<user>/northern-lights.licence.zip
        dest: "/var/home/{{ customer.user }}/northern-lights.licence"
#        remote_src: yes
 #       creates: "/var/home/{{ customer.user }}/northern-lights.licence"
