---
- name: Setup Fedora Workstation with stuffs
  hosts: localhost
  become: yes

  vars:
    local_user: admin

  tasks:

  - name: Update all software on system to current latest 
    ansible.builtin.dnf:
      name: "*"
      state: latest

  - include: "{{ playbook_dir }}/install-defaults.yml"
  - include: "{{ playbook_dir }}/install-sqlwb.yml"


  - name: Install PowerLine
    ansible.builtin.dnf: 
      name: ['powerline', 'powerline-fonts']

  - name: Allow editing on an SELinux enforced system
    ansible.builtin.dnf:
      name: libselinux-python
      state: latest

  - name: "download script for custom bashrc, profile"
    get_url:
      url: "https://raw.githubusercontent.com/rogrwhitakr/northern-lights/master/script/setup-profile-on-new-box.bash"
      dest: "/home/{{ local_user }}/profile-setup.bash"
      mode: 0740
      owner: "{{ local_user }}"
      group: "{{ local_user }}"

  - name: Run the script
    become_user: "{{ local_user }}"
    script: "/home/{{ local_user }}/profile-setup.bash"
    args:
      executable: /usr/bin/bash
      creates: "/home/{{ local_user }}/.bashrc.d"


  - name: edit .bashrc to enable powerline usage
    blockinfile:
      path: /home/{{ local_user }}/.bashrc
      block: |
        if [ -f `which powerline-daemon` ]; then
          powerline-daemon -q
          POWERLINE_BASH_CONTINUATION=1
          POWERLINE_BASH_SELECT=1
          . /usr/share/powerline/bash/powerline.sh
        fi
