---
- name: Setup Fedora Workstation with stuffs
  hosts: 192.168.178.155
  become: true

  tasks:

  - name: Update all software on system to current latest 
    ansible.builtin.dnf:
      name: "*"
      state: latest

  - name: Remove "old" Docker packages
    ansible.builtin.dnf:
      name:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-selinux
        - docker-engine-selinux
        - docker-engine
      state: absent

  - name: Install dnf-plugins-core
    ansible.builtin.dnf:
      name: dnf-plugins-core
      state: present

  - name: Add Docker repository
    ansible.builtin.command:
      cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

  - name: Install Docker and plugins
    ansible.builtin.dnf:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present

  - name: Create Docker group
    ansible.builtin.group:
      name: docker
      state: present

  - name: Add current user to Docker group
    ansible.builtin.user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

  - name: Start Docker service
    ansible.builtin.service:
      name: docker
      state: started

  - name: Check Docker logging driver
    ansible.builtin.command:
      cmd: docker info --format '{{.LoggingDriver}}'
    register: logging_driver_before

  - name: Update Docker daemon.json for journald logging
    ansible.builtin.copy:
      dest: /etc/docker/daemon.json
      content: |
        {
          "log-driver": "journald",
          "log-opts": {
            "tag": "docker/{{.Name}}"
          }
        }

  - name: Restart Docker to apply logging changes
    ansible.builtin.service:
      name: docker
      state: restarted

  - name: Check Docker logging driver
    ansible.builtin.command:
      cmd: docker info --format '{{.LoggingDriver}}'
    register: logging_driver_after

  - name: Show the value of before
    ansible.builtin.debug:
      var: logging_driver_before

  - name: Show the value of after
    ansible.builtin.debug:
      var: logging_driver_after

  - name: Restart rsyslogd
    ansible.builtin.service:
      name: syslog
      state: restarted

  - name: Set timezone to Europe/Berlin
    ansible.builtin.command:
      cmd: timedatectl set-timezone Europe/Berlin
