---
- name: Shutdown a remote computer
  vars_prompt:
    - name: host
      prompt: What box to shut down?

  gather_facts: false
  hosts: "{{ host }}"
  become: true

  tasks:
    - name: user-instigated shutdown of "{{ host }}"
      command: /sbin/shutdown -h +1
