---
- name: Shutdown a remote computer
  vars_prompt:
  - name: host
    prompt: What box to shut down?

  gather_facts: no
  hosts: "{{ host }}"
  remote_user: admin 
  become: yes
  become_method: sudo

# handle gracefully - this works, unsure why !!! 
  tasks:
 # - name: wait for ssh to go down
  #  local_action: wait_for host={{ ansible_hostname }} port=22 state=stopped  

    # shutdown one minute from now
  - name: user-instigated shutdown of "{{ host }}"
    command: /sbin/shutdown -h +1 
