
---
northernlights:
  hosts:
    server:
      ansible_user: admin
      ansible_become: yes
    powershell:
      ansible_ssh_private_key_file: ~/.ssh/bluesun.pem
    ubuntu:
      ansible_user: posix      
      ansible_become: yes

common:
  hosts:
    shares.northernlights.io