#   - Groups of hosts are delimited by [header] elements
#   - You can enter hostnames or ip addresses
#   - A hostname/ip can be a member of multiple groups

---
all:
# apparently, having a dash ("-") in a group name is not allowed
northernlights:
  hosts:
    domain.fritz.box:
      ansible_user: admin
      ansible_become: yes
    storage.fritz.box:
      ansible_user: admin
      ansible_become: yes
    elk.fritz.box:
      ansible_user: admin
      ansible_become: yes
    redmine.fritz.box:
      ansible_user: redmine
      ansible_become: yes

commons:        
  hosts:
    domain.fritz.box:
    elk.fritz.box:
    storage.fritz.box:
#    redmine.fritz.box:

authentication-server:
  hosts:
    domain.fritz.box:

storage-server:
  hosts:
    storage.fritz.box:

build-server:
  hosts:
    redmine.fritz.box:

remote-server:
  hosts:
    domain.fritz.box: