#   - Groups of hosts are delimited by [header] elements
#   - You can enter hostnames or ip addresses
#   - A hostname/ip can be a member of multiple groups

---
all:
# apparently, having a dash ("-") in a group name is not allowed
northernlights:
  hosts:
    domain.northern-lights.one:
      ansible_user: admin
      ansible_become: yes
    storage.northern-lights.one:
      ansible_user: admin
      ansible_become: yes
    elk.northern-lights.one:
      ansible_user: admin
      ansible_become: yes
    redmine.northern-lights.one:
      ansible_user: redmine
      ansible_become: yes

commons:        
  hosts:
    domain.northern-lights.one:
    elk.northern-lights.one:
#    redmine.northern-lights.one:

authentication-server:
  hosts:
    domain.northern-lights.one:

storage-server:
  hosts:
    storage.northern-lights.one:

build-server:
  hosts:
    redmine.northern-lights.one: