---
- name: Variable configuration
  include: variables.yml

- name: Setup/install tasks
  include: setup.yml

- name: initialize tasks
  include: initialize.yml

- name: configure tasks
  include: configure.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

# Configure PostgreSQL.
- import_tasks: users.yml
- import_tasks: databases.yml
- import_tasks: users_props.yml
