---
# defaults file for nextcloud

install:
  - nginx
  - php 
  - php-gd 
  - php-mbstring 
  - php-intl
  - php-pecl-apcu 
  - php-pdo 
  - php-pecl-redis 
  - php-opcache 
  - php-imagick 
  - php-zip 
  - php-process
  - php-apcu
  - php-pgsql

nginx_port: 80
nginx_user: nginx
nginx_group: nginx
nginx_password: nginx
nginx:
    server_name: 'storage'
    port: 80
    root: '/var/www/html'

nextcloud:
    archive: https://download.nextcloud.com/server/releases/nextcloud-20.0.4.tar.bz2
    trusted_domains: 
      - 'storage.northern-lights.one'
      - '192.168.0.60'
      - 'localhost'
    datadirectory: '/usr/share/nginx/html/nextcloud/data'  
    appsdirectory: '/usr/share/nginx/html/nextcloud/apps'  
    dbtype: pgsql
    dbhost: localhost
    dbname: nextcloud
    dbuser: nextcloud
    dbpassword: nextcloud