---
# defaults file for nextcloud

ansible_python_interpreter: /usr/bin/python3

install:
  - nginx
  - php 
  - php-gd 
  - php-mbstring 
  - php-intl
  - php-pecl-apcu 
  - php-pdo 
  - php-pecl-redis 
  - php-opcache 
  - php-imagick 
  - php-zip 
  - php-process
  - php-apcu
  - php-pgsql

nginx:
    server: 'storage'
    tls_port: 443
    port: 80
    user: nginx
    group: nginx
    password: nginx
    root: '/usr/share/nginx/html'
    log: '/var/log/nginx'
    cert: '/etc/ssl/certs/nextcloud.fritz.box.rsa.crt'
    key: '/etc/ssl/certs/nextcloud.fritz.box.rsa.key'
    made_comme_ca: 'openssl req -new -newkey rsa:4096 -x509 -sha256 -nodes -out nextcloud.fritz.box.rsa.crt -keyout nextcloud.fritz.box.rsa.key'

nextcloud:
    archive: https://download.nextcloud.com/server/releases/nextcloud-23.0.0.tar.bz2
    trusted_domains: 
      - 'storage.northern-lights.one'
      - 'storage.fritz.box'
      - 'fritz.box'
      - 'localhost'
    datadirectory: '/usr/share/nginx/html/nextcloud/data'  
    appsdirectory: '/usr/share/nginx/html/nextcloud/apps'  
    dbtype: pgsql
    dbhost: localhost
    dbname: nextcloud
    dbuser: nextcloud
    dbpassword: nextcloud
    admin: admin
    admin_password: vasques