---
#- name: Fedora | Enabling RPM Fusion Repos
#  yum_repository:
#    gpgcheck: no
#    baseurl: "{{ guacamole_redhat_fusion_repos }}"
#    state: present
#  become: true
#  register: result
#  until: result is successful

- name: "dnf : enable installs from free and non-free rpmfusion"
  ansible.builtin.dnf:
    name: "{{ rpmfusion }}"
    state: present
    disable_gpg_check: yes
  when:
    - ansible_facts['pkg_mgr'] == "dnf"
    - ansible_facts['distribution'] == 'Fedora'
  become: true

- name: redhat | Installing Guacamole Pre-Reqs
  ansible.builtin.dnf:
    name: "{{ guacamole_redhat_pre_reqs }}"
    state: present
  become: true
  register: result
  until: result is successful
