---
- name: "atomic systems: Update all software on system to current latest"
  shell: |                           
   rpm-ostree update
  when:
    - ansible_facts['pkg_mgr'] == "atomic_container"



- name: Install basic software
  shell: |                           
   rpm-ostree install --idempotent \
      htop \
      nmap \
      nano
  when:
    - ansible_facts['pkg_mgr'] == "atomic_container"    