---
- name: "dnf : install apps"
  block:
  - name: "dnf : Update all software on system to current latest"
    ansible.builtin.dnf:
      name: "*"
      state: latest

  - name: "dnf : Install basic software"
    ansible.builtin.dnf:
      name: "{{ basic }}"
      state: present

  - name: "dnf : Install development software"
    ansible.builtin.dnf:
      name: "{{ development }}"
      state: present
      disable_gpg_check: yes

  - name: "dnf : Update GNOME softwares"
    ansible.builtin.dnf:
        name: "{{ gnome }}"
        state: present

  - name: "dnf : Update ansible"
    ansible.builtin.dnf:
        name: "{{ ansible }}"
        state: present

  - name: "dnf : Update productivity softwares"
    ansible.builtin.dnf:
        name: "{{ productivity }}"
        state: present

  - name: "Remove unwanted default packages" 
    ansible.builtin.dnf: 
      name: "{{ removal }}"
      state: absent
      
  - name: "dnf : Install virtualisation softwares" 
    ansible.builtin.dnf: 
      name: "{{ virtualisation }}"
      state: present
  when:
  - ansible_facts['pkg_mgr'] == "dnf"

- name: "atomic systems : install apps"
  block:
  - name: "atomic systems: Install basic software"
    community.general.rpm_ostree_pkg:
      name: "{{ basic }}"
      state: present
  when:
  - ansible_facts['pkg_mgr'] == "atomic_container"