---

- name: "Display desktop Env data"
  ansible.builtin.debug:
    msg:
    - "OS: {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
    - "IP Address: {{ ansible_default_ipv4.address }}"
    - "Desktop Env: {{ lookup('ansible.builtin.env', 'DESKTOP_SESSION', default='G-N-O-M-E') }}"

- name: "install apps"
  block:
  - name: "Install misc apps"
    include_tasks: "apps.yml"
  - name: "Install VS Code"
    include_tasks: "vscode.yml"
  - name: "Install Spotify"
    include_tasks: "spotify.yml"

- name: "install workstation classic"
  block: 
  - name: "Install rpm-fusion stuffs"
    include_tasks: "rpmfusion.yml"
  when:
    - ansible_facts['pkg_mgr'] == "dnf"


- name: "install workstation atomic | silverblue"
  block: 
  - name: "run the atomic playbook"
    include_tasks: "rpm-ostree.yml"
  - name: "Install GUI applications as Flatpaks"
    include_tasks: "flatpak.yml"
  when:
    - ansible_facts['pkg_mgr'] == "atomic_container"