---
# tasks file for workstation_common
# - name: "Determine Build"
#   debug:
#    var: ansible_facts

- name: "install workstation classic"
  block: 

  - name: "Install rpm-fusion stuffs"
    include_tasks: "rpmfusion.yml"

  - name: "Install misc apps"
    include_tasks: "apps.yml"

  - name: "Install VS Code and Powershell"
    include_tasks: "vscode.yml"

  - name: "Install Spotify"
    include_tasks: "spotify.yml"

  when:
    - ansible_facts['pkg_mgr'] == "dnf"


- name: "install workstation atomic | silverblue"
  block: 
  - name: "run the atomic playbook"
    include_tasks: "rpm-ostree.yml"

  - name: "Install misc apps"
    include_tasks: "apps_atomic.yml"

  - name: "Install GUI applications as Flatpaks"
    include_tasks: "flatpak.yml"

  - name: "Install VS Code"
    include_tasks: "vscode_atomic.yml"

  - name: "Install Spotify"
    include_tasks: "spotify.yml" 
  when:
    - ansible_facts['pkg_mgr'] == "atomic_container"
