---
- name: "FLATPAK: install SPOTIFY"
  block: 
  - name: "Add the flathub flatpak repository remote to the system installation"
    community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  - name: "Install flatpak for spotify"
    community.general.flatpak:
      name: com.spotify.Client
      state: present
  - name: "Install flatpak for signal"
    community.general.flatpak:
      name: org.signal.Signal
      state: present    
  when:
    - ansible_facts['pkg_mgr'] == "dnf"

- name: "FLATPAK: install SPOTIFY"
  block:
  - name: "Add the flathub flatpak repository remote to the system installation"
    community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  - name: "Install flatpak for spotify"
    community.general.flatpak:
      name: com.spotify.Client
      state: present
  when:
    - ansible_facts['pkg_mgr'] == "atomic_container"    