---

- name: "Install VS Code"
  block:
  - name: Add Repository for Microsoft VS CODE
    yum_repository:
      name: code
      description: Visual Studio Code
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
      gpgcheck: yes
      
  - name: Install visual studio code
    ansible.builtin.dnf: 
      name: code
      state: latest

  - name: Add Repository for Powershell
    yum_repository:
      name: packages-microsoft-com-prod
      description: Microsoft Repository
      baseurl: "https://packages.microsoft.com/config/rhel/8/prod.repo"
  when:
  - ansible_facts['pkg_mgr'] == "dnf"

- name: "Install VS Code (flatpak)"
  block:
  - name: Install visual studio code
    flatpak:
      name: code
      state: present
  when:
  - ansible_facts['pkg_mgr'] == "atomic_container"