---

- name: "Download nextcloud programme binaries"
  unarchive:
    src: "{{ nextcloud.archive }}"
    dest: /usr/share/nginx/html
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    remote_src: yes

- name: "copy nextcloud configuration file"
  template:
    src: config.php.j2
    dest: /usr/share/nginx/html/nextcloud/config/config.php
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: u=rw,g=r,o=r
  notify: restart nginx
  tags: config


- name: "execute this command"
  ansible.builtin.command: /usr/bin/php occ maintenance:install
  become: yes
  become_user: "{{ nginx_user }}"
  argv:
   - --data-dir /usr/share/nginx/html/nextcloud/data/ 
   - --database {{ nextcloud.dbtype }} 
   - --database-name {{ nextcloud.dbname }} 
   - --database-user {{ nextcloud.dbuser }} 
   - --database-pass {{ nextcloud.dbpassword }} 
   - --admin-user {{ nextcloud.admin }} 
   - --admin-pass {{ nextcloud.admin_password }} 
  chdir: /usr/share/nginx/html/nextcloud
  tags: config  

  