---
# defaults file for docker

ansible_python_interpreter: /usr/bin/python3

# docker community edition
docker_ce:
  - 'docker-ce' 
  - 'docker-ce-cli' 
  - 'containerd.io'
  - 'docker-buildx-plugin' 
  - 'docker-compose-plugin'

# for removal if exists
docker_io:
  - 'docker'
  - 'docker-client'
  - 'docker-client-latest'
  - 'docker-common'
  - 'docker-latest'
  - 'docker-latest-logrotate'
  - 'docker-logrotate'
  - 'docker-selinux'
  - 'docker-engine-selinux'
  - 'docker-engine'