- name: HOW TO DO STUFF WITH FILES
  hosts: cortez magellan
  remote_user: admin
  become: yes
  vars:
    fileName: file-touched-by-ansible
    version: "0.15.3"

  tasks:
    - name: Create a file
      file:
        path: /tmp/{{ fileName }}.txt
        state: touch
        mode: 0644

    - name: edit a file
      lineinfile:
        path: /tmp/{{ fileName }}.txt
        line: added a single line

    - name: add another line
      lineinfile:
        path: /tmp/{{ fileName }}.txt
        line: added a single line

    - name: blockedit a file
      blockinfile:
        path: /tmp/{{ fileName }}.txt
        block: |
          if [ -f `which powerline-daemon` ]; then
            powerline-daemon -q
            POWERLINE_BASH_CONTINUATION=1
            POWERLINE_BASH_SELECT=1
            . /usr/share/powerline/bash/powerline.sh
          fi

    - name: Copy a [remote] file to a [remote] destination
      copy:
        remote_src: yes
        backup: yes
        src: /tmp/{{ fileName }}.txt
        dest: /usr/local/bin/{{ fileName }}.txt
        mode: 0755

    - name: Copy a [local] file to a [remote] destination
      copy:
        src: /home/admin/MyScripts/apps/ansible/src/unit-file.service
        dest: /tmp/unit-file.service
        
        # does not work at the moment
        # validate: /usr/bin/systemd-analyze verify %s

    - name: Copy a [local] file to a [remote] destination, and validate it
      copy:
        src: src/wall-message.txt
        dest: /tmp/wall-message.txt

    # optional but possible:
    #   owner: "{{userId}}"
    #   group: "{{groupId}}"

    - name: "remove a file > file created in /tmp will be removed"
      file:
        path: /tmp/{{ fileName }}.txt
        state: absent

    - name: Download a programme
      unarchive:
        src: "https://github.com/prometheus/alertmanager/releases/download/v{{ version }}/alertmanager-{{ version }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes

    - name: "Copy alertmanager executable to bin :: INSTALL"
      copy:
        src: "/tmp/alertmanager-{{ version }}.linux-amd64/alertmanager"
        dest: "/usr/local/bin/alertmanager"
        remote_src: yes
        mode: 0755

    - name: Delete alertmanager tmp folder
      file:
        path: "/tmp/alertmanager-{{ version }}.linux-amd64"
        state: absent

    - name: "create a deep directory"
      file:
        path: /home/admin/conf.d/sub-conf.d/more-sub-conf.d/a/b/c/d
        state: directory
        owner: admin
        group: admin
        mode: 0755 
      tags: deep-dir

    - name: "create a file wihtin that deep directory, can i do this in one play? conditionals?"
      file:
        path: "/home/admin/conf.d/sub-conf.d/more-sub-conf.d/a/b/c/d/{{ ansible_facts['nodename'] }}"
        state: touch
        owner: admin
        group: admin
        mode: 0755         
      tags: deep-dir

    - name: "remove a deep directory"
      file:
        path: /home/admin/conf.d
        state: absent
      tags: deep-dir

    # [-------------------------------------------]
    #  create a file and add content
    #  two ways
    #   - touch + lineinfile / blockinfile
    #   - use the copy module
       
    - name: "creating a file with content using the copy module"
      copy:
        dest: "/tmp/file-on-{{ ansible_facts['nodename'] }}-with-content.txt"
        content: |
          # access available tasks
          ansible-playbook MyScripts/apps/ansible/_modules.user.yml --list-tags

          # execute specific sections of playbook using a tag (-t / --tags flag)
          ansible-playbook MyScripts/apps/ansible/_modules.user.yml --ask-become-pass -t ftp_user
      tags: create_and_add_content    

    - name: create content using copy module and a json feed
      copy: 
        content: "{{ your_json_feed }}" 
        dest: "/tmp/file-on-{{ ansible_facts['nodename'] }}-with-json-feed.txt"

    - name: "unsure if still viable...:Ansible create multiple files example"
      file: 
        path: "/tmp/{{ item }}"
        state: touch
        mode: 0775
      with_items:
      - int1.txt
      - int2.txt
      - int3.txt
      - int4.txt    