---
- name: EXPLAINER FOR FETCHING FILES FROM REMOTE SYSTEMS - USING FETCH MODULE
  hosts: magellan
  remote_user: admin

  tasks:
  - name: fetch file from remote, write content to /tmp/ansible/magellan/home/admin/.bashrc 
    fetch:
      src: /home/admin/.bashrc
      dest: /tmp/ansible

  - name: "fetch a file, write its content to a file named {{ dest }}" 
    fetch: 
      src: /home/admin/.bash_history
      dest: /tmp/ansible/prefix-{{ ansible_facts['nodename'] }}
      flat: yes

  - name: "fetch a file, write its content to a file named dest_dir / .bash_profile"
    fetch:
      src: /home/admin/.bash_profile
      dest: /tmp/ansible/
      flat: yes

  - name: Storing in a path relative to the playbook
    fetch:
      src: /home/admin/.bash_logout
      dest: special/prefix-{{ inventory_hostname }}
      flat: yes