---
- name: EXPLAINER FOR DEBUGGING / MESSAGE FROM SYSTEMS - HOW TO
  hosts: magellan
  remote_user: admin
  become: yes

  tasks:
    - name: "do something: make a file"
      file:
        path: /tmp/file-made-with-debugging-playbook.on-{{ ansible_facts['nodename'] }}.txt
        state: touch
        mode: 0644
      tags: something

    - debug: 
        var: ansible_facts.distribution
    - debug:    
        var: ansible_facts.selinux.status
    - debug:    
        var: ansible_facts['selinux']['status']

    # [-----------------------------------------]
    # as is known, one may disable the fact gathering by adding to playbook
    #   - hosts: host_everything_is_known_about
    #     gather_facts: no
    # (may increase scaling factor when managing a large number of remotes)
      
    - name: feed back that info
      debug:
        msg: ""

    - name: register file contents
      slurp:
        src: /etc/os-release
      register: release

    - name: Print Release Information
      debug: 
        msg: "{{ release['content'] | b64decode }}"        
