
---
- name: MANAGING USERS INFO
  hosts: cortez
  become: yes

  vars_files:
    - /home/admin/MyScripts/apps/ansible/src/ext_user_var.yml

  tasks:
    - name: Creating user group 
      group: name="{{group_no_login}}"
      become: true  
      tags: "no_login"

    - name: Creating a nologin system user
      user:
        name: "{{user_no_login}}"
        group: "{{group_no_login}}"
        system: yes
        shell: "/sbin/nologin"
        comment: "{{user_no_login}} nologin User"
        createhome: "no"
        state: present
      tags: "no_login"

    - name: Creating user group to be used in a FTP session
      group: name="{{group}}"
      become: true
      tags: "ftp_user"

    - name: create a user to be used in a FTP session
      user:
        name: "{{user}}"
        group: "{{group}}"
        password: "{{password}}"
        system: yes
        comment: "{{user}} for FTP"
        createhome: yes
        state: present    
      tags: "ftp_user"

#- name: Check if user exists
#  command: getent passwd neelix
#  register: neelix_on_board
#  ignore_errors: yes # continue with the playbook

#- name: Add user to list of active users
#  lineinfile:
#    name: /etc/docking_bay/allowed_users
#    line: Neelix
#  when: neelix_on_board.rc == 0        