
---
- name: Setup test server
  hosts: cortez
  remote_user: admin
  become: yes

  tasks:
  - name: update all packages
    dnf:
      name: "*"
      state: latest

  - name: get release info
    slurp:
      src: /etc/os-release
    register: fedora
  - debug:
    msg: "{{ fedora['content'] | b64decode }}"

  - name: Install basics
    dnf: name={{item}} state=present
    with_items:
    - nano
    - python3
    - python

  - name: Install monitoring software
    dnf: name={{item}} state=present
    with_items:
    - htop
    - sysstat
    - iotop
    - dmidecode

  - name: Install databases
    dnf: name={{item}} state=present
    with_items:
    - postgresql
    - postgresql-server
    - mariadb
    
  - name: Install LDAP server
    dnf: name={{item}} state=present
    with_items:
    - openldap 
    - openldap-clients
    - openldap-servers
    
  - name: Install SFTP server
    dnf: name={{item}} state=present
    with_items:
    - vsftpd
