---

- name: "Download nextcloud programme binaries"
  unarchive:
    src: "{{ nextcloud }}"
    dest: /usr/share/nginx/html
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    remote_src: yes

- name: "copy nextcloud configuration file"
  template:
    src: config.php.j2
    dest: /usr/share/nginx/html/nextcloud/config/config.php
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: u=rw,g=r,o=r
  notify: restart nginx