---
# defaults file for ansible-guacamole
ansible_python_interpreter: /usr/bin/python3

# Authentication
guacamole_auth_jdbc_package: "{{ 'guacamole-auth-jdbc-' + guacamole_version + '.tar.gz' }}"
guacamole_auth_provider: net.sourceforge.guacamole.net.basic.BasicFileAuthenticationProvider
guacamole_client_package: "{{ 'guacamole-' + guacamole_version + '.war' }}"
guacamole_dl_url: "{{ 'http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/' + guacamole_version }}"
guacamole_server_hostname: localhost

# Authentication OpenID
guacamole_openid_auth: false
guacamole_auth_openid_package: "{{ 'guacamole-auth-openid-' + guacamole_version + '.tar.gz' }}"
guacamole_auth_openid_priority: ""

# Defines if PostgreSQL DB should be used for authentication
guacamole_postgresql_auth: true
guacamole_postgresql_connector_package: "{{ guacamole_postgresql_connector_dl_url + 'postgresql-' + guacamole_postgresql_connector_version + '.jar' }}"
guacamole_postgresql_connector_dl_url: https://jdbc.postgresql.org/download/
guacamole_postgresql_connector_version: 42.2.20

# Define PostgreSQL DB Info
guacamole_postgresql_db:
  name: guacamole
  host: localhost
  port: 5432
  username: guacamole
  password: guacamole
  auto-create-accounts: true

# Define OpenID Info
guacamole_openid:
  authorization-endpoint:
  jwks-endpoint:
  issuer:
  client-id:
  redirect-uri:
  username-claim-type: preferred_username
  groups-claim-type: groups
  allowed-clock-skew: 500

# RDP settings
guacamole_rdp_color_depth: 24
guacamole_rdp_disable_auth: false
guacamole_rdp_height: 900
guacamole_rdp_width: 1440
guacamole_rdp_security: rdp
guacamole_rdp_ignore_cert: false

rpmfusion:
  - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm 
  - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

guacamole_github: 'git://github.com/apache/guacamole-server.git'

guacamole_server_package: "{{ 'guacamole-server-' + guacamole_version + '.tar.gz' }}"

guacamole_server_port: 4822

#guacamole_basic_user_mapping: /etc/guacamole/user-mapping.xml

guacamole_src_dir: /usr/local/src

# Define version to install
guacamole_version: 1.3.0
