
# using a prompt

  vars_prompt:
    - name: api_key
      prompt: Enter the API key
  tasks:
    - name: Ensure API key is present in config file
      ansible.builtin.lineinfile:
        path: /etc/app/configuration.ini
        line: "API_KEY={{ api_key }}"
      no_log:
      # this ensures nothing is logged in plain text!
      
# using ansible vault

# create a secrets_file -> secret.vault
# contains
# api_key: SuperSecretPassword

# Encrypt the file with ansible-vault
# ansible-vault encrypt secrets.vault

# execute playbook
# ansible-playbook -i inventory.ini -e @secret.vault --ask-vault-pass main.yml 

# modify, decrpyt the file with ansible-vault
# ansible-vault decrypt secrets.vault
# ansible-vault edit secrets.vault

