---
- name: how to use services and handlers 
  hosts: cortez magellan
  remote_user: admin
  become: yes

  tasks:
    - name: Update and restart ssh if it is updated
      ansible.builtin.dnf:
        name: "httpd"
        state: latest
      notify:
        - name: restart Apache

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Check if web server is accessible
      uri:
        url: http://cortez:80
        method: GET
        status_code: 200
