- name: _MODULES MOUNT
  hosts: localhost
  become: yes

  tasks:

  - name: "get me some specific data" 
    debug: 
      var: ansible_facts['env']['SUDO_GID'], ansible_facts['env']['SUDO_UID']

  - block:
    - name: "ensure '/mnt/share' directory exists and is owned by {{ ansible_facts['env']['SUDO_USER'] }}"
      file:
        path: /mnt/share
        state: directory
        owner: "{{ ansible_facts['env']['SUDO_USER'] }}"
        group: "{{ ansible_facts['env']['SUDO_USER'] }}"
        mode: 0777
# unsure as to why, but this bit down not work. probably something with priviledges

    - name: "add mount to windows share on host FINCH"
      mount:
        name: /mnt/share
        src: //192.168.0.100/share
        opts: "user=HaroldFinch,password=vasques,domain=WORKGROUP,file_mode=0777,dir_mode=0777,uid={{ ansible_facts['env']['SUDO_UID'] }},gid= {{ ansible_facts['env']['SUDO_GID'] }}"
        fstype: cifs
        state: mounted