---
- name: Install basic software
  dnf: 
    name: ['htop', 'nmap', 'nano']

- name: Install system / analytics software
  dnf: 
    name: ['dconf-editor', 'firewalld', 'wireshark']

- name: Install all that cool but obscure stuff one 'might' need
  dnf: 
    name: ['dstat', 'nmap', 'dmidecode', 'strace', 'powertop', 'atop', 'glances', 'mtr', 'iftop', 'nethogs']

- name: Install database (client) software
  dnf: 
    name: ['sequeler', 'postgresql']

- name: Install Python Environment 
  dnf: 
    name: ['python3', 'python3-mypy']
    
- name: Install Productivity software
  dnf: 
    name: ['chromium', 'firefox', 'calibre']            