---
- name: Setup Fedora Workstation with stuffs
  hosts: localhost
  remote_user: admin
  become: yes

  tasks:
  - name: Install Virtualisation software
    ansible.builtin.dnf: name={{item}} state=present
    with_items:
    - virsh
    - virt-manager