---
- name: Install Powerline globally for all users
  hosts: all
  become: yes

  tasks:
    - name: Ensure Powerline packages are installed system-wide
      ansible.builtin.dnf:
        name:
          - powerline
          - powerline-fonts
          - python3-libselinux
        state: present

    - name: Configure /etc/bashrc to enable Powerline for all users
      ansible.builtin.blockinfile:
        path: /etc/bashrc
        block: |
          # The following lines were added by Ansible for Powerline
          if [ -f `which powerline-daemon` ]; then
            powerline-daemon -q
            POWERLINE_BASH_CONTINUATION=1
            POWERLINE_BASH_SELECT=1
            . /usr/share/powerline/bash/powerline.sh
          fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK - POWERLINE"
        insertafter: EOF