---
- name: Setup Fedora Workstation with stuffs
  hosts: localhost
  remote_user: admin
  become: yes

  tasks:
  - debug:
      msg: "{{ ansible_facts['virtualization_role'] }}"

  - name: Install Virtualisation software
    ansible.builtin.dnf: name={{item}} state=present
    with_items:
    - nano
    - htop
    when: ansible_facts['virtualization_role'] == "guest" and ansible_facts['virtualization_type'] == "kvm"